FROM almalinux:9
CMD [ "google.com" ]
ENTRYPOINT [ "ping","-c5" ]

# CMD instruction can be overriden from runtime
# entrypoint instrection can't be overriden but it will apend the info which we gave in runtime