ARG version
FROM almalinux:${version}
ARG Name
ARG Tool
RUN echo "This is ${Name}, practicing ${Tool}"
CMD [ "sleep","100" ]

# ARG can be first instruction in only one case - beofre from to get version
#