FROM almalinux:9
ADD https://raw.githubusercontent.com/Krish121212/shell-script/main/Logfile.sh /tmp/kk.txt
CMD [ "sleep","100" ]

# Add and copy does same task, but add can also download files from internet. whereas copy = only local workspace
# it can un-tar the files
